general_configuration:
  image_size: [512, 512]
  valid_extensions: [".bmp", ".BMP"]

dataset_pipeline:
  paths:
    source_training: "D:/emanuele/Code/new_source_dataset/Training"
    source_validation: "D:/emanuele/Code/new_source_dataset/Validation"
    dest_transfer_learning: "./data/dataset_supcon"
    dest_patchcore: "./data/dataset_patchcore"

  classes:
    good_categories: ["cimossa", "dust", "good"]
    defect_categories: ["nodi", "paglie"]

  ratios:
    tl_allocation_ratio: 0.30
    good_stress_multiplier: 3
    cimossa_undersampling_ratio: 0.40

  augmentation_params:
    prob_h_flip: 0.5
    prob_v_flip: 0.5
    prob_rot_180: 0.5
    prob_stress: 0.5
    textile_intensity_range: [0.2, 0.6]
    textile_waves_range: [0.5, 0.8]
    textile_force_range: [0.0, 60.0]

paths:
  pca_cumulative_variance_plot_path: "results/EDA/pca_cumulative_variance.png"
  pca_lda_analysis_plot_path: "results/EDA/pca_lda_analysis.png"
  interactive_tsne_plot_path: "results/EDA/interactive_tsne_plot.png"
  benchmark_pareto_front_patchcore: "results/benchmark/benchmark_pareto_front_patchcore.csv"
  benchmark_pareto_front_efficientad: "results/benchmark/benchmark_pareto_front_efficientad.csv"
  checkpoint_destination: "checkpoints/patchcore-tested.ckpt"
  exports_onnx_path: "exports/patchcore_onnx"
