general_configuration:
  image_size: [512, 512]
  crop_size: [512, 512] # If the backbone is "efficientnet" the crop_size is setted as the size of the model's input
  valid_extensions: [".bmp", ".BMP"]
  flag_threshold: True # If this flag is True the manual threshold is selected, otherwise automatic threshold 
  manual_threshold: 0.6

dataset_pipeline:
  # ---------------------------------------------------------
  # Dataset Versioning
  # ALWAYS update this version whenever you recreate the dataset
  # ---------------------------------------------------------
  dataset_version: 3.0.0
  split_source: True ## Set to False if you have already splited the dataset source into training and validation
  seed: 42
  paths:
    source_unsplitted_dataset: "D:/emanuele/Code/dataset/src_dataset"
    source_training: "D:/emanuele/Code/dataset/dataset_splitted/training"
    source_validation: "D:/emanuele/Code/dataset/dataset_splitted/validation"
    dest_transfer_learning: "./data/dataset_tl"
    dest_patchcore: "./data/dataset_ad"

  classes:
    good_categories: ["good","dust"]
    test_only_good_categories: []
    defect_categories: ["nodi", "paglie"]

  ratios:
    training_ratio: 0.6
    tl_allocation_ratio: 0.4
    good_stress_multiplier: 2
    cimossa_undersampling_ratio: 0.40
    good_limit_patchcore: 300

  augmentation_params:
    prob_h_flip: 0.5
    prob_v_flip: 0.5
    prob_rot_180: 0.5
    prob_stress: 0.5
    textile_intensity_range: [0.05, 0.15]
    textile_waves_range: [2.0, 5.0]
    textile_force_range: [2.0, 8.0]

model_architecture:
  # Attention: RD4AD requires ResNet-based architectures (e.g., resnet18, resnet50, wide_resnet50_2) to properly extract hierarchical feature maps.
  backbone: "wide_resnet50_2" 
  
  # Attention: RD4AD strictly requires exactly 3 consecutive layers (layer1, layer2, layer3). 
  # This is a hard structural constraint imposed by the multi-scale One-Class Bottleneck Embedding (OCBE) block.
  layers: ["layer1", "layer2", "layer3"]
  weights: "DEFAULT"

transfer_learning:
  data_dir: "./data/dataset_supcon"
  num_epochs: 10
  batch_size: 32
  learning_rate: 0.0001
  temperature: 0.07
  out_dim: 128
  save_dir: "custom_weights"
  balancing_dataset: False

datamodule_configuration:
  root: "./data"
  train_dir: "./data/dataset_ad/train"
  test_dir_good: "./data/dataset_ad/test/good"
  test_dir_reject: "./data/dataset_ad/test/reject"
  num_workers: 4 # Standard to prevent CPU overhead. Set to 1 for patchcore

# ---------------------------------------------------------
# Model-Specific Configurations
# ONLY check and modify the section of your target model
# --------------------------------------------------------- 
patchcore_configuration:
  num_epochs: 1
  train_batch_size: 32
  eval_batch_size: 32
  coreset_sampling_ratio: 0.2
  num_nearest_neighbors: 12

efficientad_configuration:
  imagenette_dir: "./data/imagenette_for_efficientad"
  num_epochs: 50
  train_batch_size: 1 # Efficient AD require a fixed batch size equal to 1 to correctly handling the knowledge distillation
  eval_batch_size: 32
  model_size: "s"
  learning_rate: 0.0001
  weight_decay: 0.00001

reversedistillation_configuration:
  num_epochs: 1
  train_batch_size: 16
  eval_batch_size: 16


# ---------------------------------------------------------
# Output Paths
# ALWAYS check and update these paths when switching models
# (e.g., change "Patchcore" to "EfficientAD" or "RD4AD")
# ---------------------------------------------------------
paths:
  # The symbolic link (symlink) path for the latest run results.
  # Choose the path corresponding to the active model architecture:
  # - For RD4AD: results/ReverseDistillation/textiles_dataset/latest
  # - For Patchcore: results/Patchcore/textiles_dataset/latest
  # - For EfficientAD: results/EfficientAD/textiles_dataset/latest
  symlink_path: "results/ReverseDistillation/textiles_dataset/latest"
  anomaly_images: "results/ReverseDistillation/anomaly_images"
  report_path: "results/ReverseDistillation/report"
  auroc_path: "results/ReverseDistillation/AUROC"
  eda_path: "results/EDA"
  benchmark_pareto_front_patchcore: "results/benchmark/benchmark_pareto_front_patchcore.csv"
  benchmark_pareto_front_efficientad: "results/benchmark/benchmark_pareto_front_efficientad.csv"
  checkpoint_destination: "checkpoints/rd4ad-tested.ckpt"
  exports_onnx_path: "exports/rd4ad_onnx"
  exports_pt_path: "exports/rd4ad_pt"
  config_src_path: "config.yaml"
  config_dst_path: "results/ReverseDistillation/config"
